title: EO Framework
description: Exceptional Outcome Framework for Community Collaboration
baseurl: "/eof-website"
url: "https://eoframework.github.io"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag